version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class : logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: main.log
    maxBytes: 1024
    backupCount: 3
root:
  level: INFO
  handlers: [console, file]
